import { IconTypes } from '../enums/IconTypes.enum';
import { COUNTER_TYPE } from './CounterType.constants';

export const LANDING_DOMAINS = [
  { name: 'Medical', icon: IconTypes.USERS },
  { name: 'Jurnalism', icon: IconTypes.USERS },
  { name: 'Educație', icon: IconTypes.USERS },
  { name: 'Inginerie', icon: IconTypes.USERS },
  { name: 'Tech', icon: IconTypes.USERS },
  { name: 'Advocacy', icon: IconTypes.USERS },
];

export const LANDING_COUNTER_ITEMS = [
  { value: '3500+', type: COUNTER_TYPE.PROGRAMS },
  { value: '500+', type: COUNTER_TYPE.NGOS },
];

export const PRACTICE_PROGRAMS = {
  meta: {
    itemCount: 5,
    totalItems: 5,
    itemsPerPage: 5,
    totalPages: 1,
    currentPage: 1,
  },
  items: [
    {
      id: 1,
      organization: { id: 1, organizationGeneral: { name: 'Organizatia ONG' } },
      title: 'Titlu scurt de program de practica',
      deadline: new Date('2022-11-01T20:00:00.000Z'),
      location: {
        id: 1,
        name: '1 Decembrie',
      },
      startDate: new Date('2022-12-31T20:00:00.000Z'),
      endDate: null,
      minWorkingHours: 60,
      maxWorkingHours: 70,
      link: 'www.test.com',
      description: 'Asta este o descriere a unui program de preactica',
      skills: [],
      domains: [],
      faculties: [],
    },
    {
      id: 2,
      organization: { id: 1, organizationGeneral: { name: 'Organizatia ONG' } },
      title: 'Titlu scurt de program de practica',
      deadline: null,
      location: {
        id: 1,
        name: '1 Decembrie',
      },
      startDate: new Date('2022-11-20T20:00:00.000Z'),
      endDate: new Date('2022-12-31T20:00:00.000Z'),
      minWorkingHours: 60,
      maxWorkingHours: 70,
      link: 'www.test.com',
      description: 'Asta este o descriere a unui program de preactica',
      skills: [],
      domains: [],
      faculties: [],
    },
    {
      id: 3,
      organization: { id: 1, organizationGeneral: { name: 'Organizatia ONG' } },
      title: 'Titlu scurt de program de practica',
      deadline: new Date('2022-11-01T20:00:00.000Z'),
      location: {
        id: 1,
        name: '1 Decembrie',
      },
      startDate: new Date('2022-11-20T20:00:00.000Z'),
      endDate: new Date('2022-12-31T20:00:00.000Z'),
      minWorkingHours: 60,
      maxWorkingHours: 70,
      link: 'www.test.com',
      description: 'Asta este o descriere a unui program de preactica',
      skills: [],
      domains: [],
      faculties: [],
    },
    {
      id: 4,
      organization: { id: 1, organizationGeneral: { name: 'Organizatia ONG' } },
      title: 'Titlu scurt de program de practica',
      deadline: new Date('2022-11-01T20:00:00.000Z'),
      location: {
        id: 1,
        name: '1 Decembrie',
      },
      startDate: new Date('2022-11-20T20:00:00.000Z'),
      endDate: new Date('2022-12-31T20:00:00.000Z'),
      minWorkingHours: 60,
      maxWorkingHours: 70,
      link: 'www.test.com',
      description: 'Asta este o descriere a unui program de preactica',
      skills: [],
      domains: [],
      faculties: [],
    },
    {
      id: 5,
      organization: { id: 1, organizationGeneral: { name: 'Organizatia ONG' } },
      title: 'Titlu scurt de program de practica',
      deadline: new Date('2022-11-01T20:00:00.000Z'),
      location: {
        id: 1,
        name: '1 Decembrie',
      },
      startDate: new Date('2022-11-20T20:00:00.000Z'),
      endDate: new Date('2022-12-31T20:00:00.000Z'),
      minWorkingHours: 60,
      maxWorkingHours: 70,
      link: 'www.test.com',
      description: 'Asta este o descriere a unui program de preactica',
      skills: [],
      domains: [],
      faculties: [],
    },
  ],
};

export const ORGANIZATIONS = {
  meta: {
    itemCount: 6,
    totalItems: 6,
    itemsPerPage: 6,
    totalPages: 1,
    currentPage: 1,
  },
  items: [
    {
      id: 1,
      logo: '',
      name: 'Denumire Scurta ONG',
      shortDescription:
        'Short Description Short Description Short Description Short Description Short Description',
      email: 'contact1test@email.com',
      phone: '+40761355001',
      description: '',
      website: 'www.google.ro',
      facebook: 'www.facebook.com/org',
      instagram: null,
      twitter: null,
      linkedin: null,
      tiktok: null,
      city: {
        id: 3375,
        name: 'Coslogeni',
        countyId: 19,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      county: {
        id: 19,
        name: 'Calarasi',
        abbreviation: 'CL',
        regionId: 7,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      domains: [],
    },
    {
      id: 2,
      logo: '',
      name: 'Denumire Scurta ONG',
      shortDescription:
        'Short Description Short Description Short Description Short Description Short Description',
      description: '',
      email: 'contact1test@email.com',
      phone: '+40761355001',
      website: 'www.google.ro',
      facebook: 'www.facebook.com/org',
      instagram: null,
      twitter: null,
      linkedin: null,
      tiktok: null,
      city: {
        id: 3375,
        name: 'Coslogeni',
        countyId: 19,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      county: {
        id: 19,
        name: 'Calarasi',
        abbreviation: 'CL',
        regionId: 7,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      domains: [],
    },
    {
      id: 3,
      logo: '',
      name: 'Denumire Scurta ONG',
      shortDescription:
        'Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description',
      description: '',
      email: 'contact1test@email.com',
      phone: '+40761355001',
      website: 'www.google.ro',
      facebook: 'www.facebook.com/org',
      instagram: null,
      twitter: null,
      linkedin: null,
      tiktok: null,
      city: {
        id: 3375,
        name: 'Coslogeni',
        countyId: 19,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      county: {
        id: 19,
        name: 'Calarasi',
        abbreviation: 'CL',
        regionId: 7,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      domains: [],
    },
    {
      id: 4,
      logo: '',
      name: 'Denumire Scurta ONG',
      shortDescription:
        'Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description Short Description',
      description: '',
      email: 'contact1test@email.com',
      phone: '+40761355001',
      website: 'www.google.ro',
      facebook: 'www.facebook.com/org',
      instagram: null,
      twitter: null,
      linkedin: null,
      tiktok: null,
      city: {
        id: 3375,
        name: 'Coslogeni',
        countyId: 19,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      county: {
        id: 19,
        name: 'Calarasi',
        abbreviation: 'CL',
        regionId: 7,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      domains: [],
    },
    {
      id: 5,
      logo: '',
      name: 'Denumire Scurta ONG',
      shortDescription:
        'Short Description Short Description Short Description Short Description Short Description',
      description: '',
      email: 'contact1test@email.com',
      phone: '+40761355001',
      website: 'www.google.ro',
      facebook: 'www.facebook.com/org',
      instagram: null,
      twitter: null,
      linkedin: null,
      tiktok: null,
      city: {
        id: 3375,
        name: 'Coslogeni',
        countyId: 19,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      county: {
        id: 19,
        name: 'Calarasi',
        abbreviation: 'CL',
        regionId: 7,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      domains: [],
    },
    {
      id: 6,
      logo: '',
      name: 'Denumire Scurta ONG',
      shortDescription:
        'Short Description Short Description Short Description Short Description Short Description',
      description: '',
      email: 'contact1test@email.com',
      phone: '+40761355001',
      website: 'www.google.ro',
      facebook: 'www.facebook.com/org',
      instagram: null,
      twitter: null,
      linkedin: null,
      tiktok: null,
      city: {
        id: 3375,
        name: 'Coslogeni',
        countyId: 19,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      county: {
        id: 19,
        name: 'Calarasi',
        abbreviation: 'CL',
        regionId: 7,
        createdOn: '2022-07-14T10:22:32.534Z',
      },
      domains: [],
    },
  ],
};

export const ORGANIZATION = {
  id: 1,
  name: 'ASOCIATIA CLUB IMOBILIAR',
  alias: 'ACI',
  type: 'foundation',
  email: 'contact1test@email.com',
  phone: '+40761355001',
  shortDescription: 'This is a simple test of 50 characters or more than that.',
  description:
    'It was a cold grey day in late November. The weather had changed overnight, when a backing wind brought a granite sky and a mizzling rain with it, and although it was now only a little after two twoo.',
  logo: '',
  website: 'www.google.ro',
  facebook: 'www.facebook.com/org',
  instagram: 'insta',
  twitter: 'twit',
  linkedin: null,
  tiktok: null,
  city: {
    id: 3375,
    name: 'Coslogeni',
    countyId: 19,
    createdOn: '2022-07-14T10:22:32.534Z',
  },
  county: {
    id: 19,
    name: 'Calarasi',
    abbreviation: 'CL',
    regionId: 7,
    createdOn: '2022-07-14T10:22:32.534Z',
  },
  domains: [
    { id: 1, name: 'social' },
    { id: 2, name: 'inginerie' },
  ],
};
